### ISSUE TITLE
Use (better) relative path for dynamic command loading

### ISSUE THREAD

**Issue by jemand771** [N-O-D-E-Community/E-D-G-E#3]
Starting the app from the project root folder works fine, but starting it from the src folder throws an error.

```
starting E-D-G-E..
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Willy\Documents\atom\E-D-G-E\src\src\cmd'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.<anonymous> (C:\Users\Willy\Documents\atom\E-D-G-E\src\app.js:9:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by SageStarCodes** [comment]
um... just don't start it from the src folder
run `npm start` from the project root
